#pragma once

#include "../SDK/interface.h"
#include "../SDK/iserverplugin.h"
#include "../SDK/igameevents.h"
#include "../SDK/convar.h"
#include "../SDK/Color.h"
#include "../SDK/tier1.h"
#include "../SDK/tier2.h"
#include "../SDK/dbg.h"
#include "../SDK/iclientmode.h"

#include "../SDK/strtools.h"
#include "../SDK/const.h"
#include "../SDK/vector.h"
#include "../SDK/vector2d.h"
#include "../SDK/vector4d.h"

#include "../SDK/icliententitylist.h"
#include "../SDK/icliententity.h"
#include "../SDK/view_shared.h"
#include "../SDK/cdll_int.h"
#include "../SDK/iinputsystem.h"
#include "../SDK/IPanel.h"
#include "../SDK/dt_common.h"
#include "../SDK/dt_recv.h"
#include "../SDK/client_class.h"